language: generic
dist: xenial
sudo: required
install:
  - scripts/provision.sh travis
  - scripts/python_setup.sh travis
  - scripts/vault_setup.sh travis
before_script:
  - source ~/.bash_profile
  - pushd python-client; pipenv install; popd
script:
  - tests/test_basic_config.sh
  - tests/test_python_config.sh
  - pushd python-client/tests; pipenv run python3 test_vault_com_kv.py
  - pipenv run python3 test_ui.py
  - popd
