language: generic
dist: xenial
sudo: required
install:
  - scripts/provision.sh travis
  - scripts/python_setup.sh travis
  - scripts/vault_setup.sh travis
before_script:
  - source ~/.bash_profile
script:
  - echo "Current user - $USER"
  - tests/test_basic_config.sh
  - tests/test_python_config.sh
